// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Biblioteca.API.Migrations
{
    [DbContext(typeof(BibliotecaAPIContext))]
    [Migration("20261002035516_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Modelos.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_autor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdAutor");

                    b.ToTable("autor");
                });

            modelBuilder.Entity("Biblioteca.Modelos.Editorial", b =>
                {
                    b.Property<int>("IdEditorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_editorial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEditorial"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pais");

                    b.HasKey("IdEditorial");

                    b.ToTable("editorial");
                });

            modelBuilder.Entity("Biblioteca.Modelos.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_genero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdGenero");

                    b.ToTable("genero");
                });

            modelBuilder.Entity("Biblioteca.Modelos.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_libro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLibro"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("integer")
                        .HasColumnName("anio_publicacion");

                    b.Property<int?>("AutorIdAutor")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EditorialIdEditorial")
                        .HasColumnType("integer");

                    b.Property<int?>("GeneroIdGenero")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("isbn");

                    b.Property<int>("IdAutor")
                        .HasColumnType("integer")
                        .HasColumnName("id_autor");

                    b.Property<int>("IdEditorial")
                        .HasColumnType("integer")
                        .HasColumnName("id_editorial");

                    b.Property<int>("IdGenero")
                        .HasColumnType("integer")
                        .HasColumnName("id_genero");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("IdLibro");

                    b.HasIndex("AutorIdAutor");

                    b.HasIndex("EditorialIdEditorial");

                    b.HasIndex("GeneroIdGenero");

                    b.ToTable("libro");
                });

            modelBuilder.Entity("Biblioteca.Modelos.Libro", b =>
                {
                    b.HasOne("Biblioteca.Modelos.Autor", "Autor")
                        .WithMany("Libro")
                        .HasForeignKey("AutorIdAutor");

                    b.HasOne("Biblioteca.Modelos.Editorial", "Editorial")
                        .WithMany("Libro")
                        .HasForeignKey("EditorialIdEditorial");

                    b.HasOne("Biblioteca.Modelos.Genero", "Genero")
                        .WithMany("Libro")
                        .HasForeignKey("GeneroIdGenero");

                    b.Navigation("Autor");

                    b.Navigation("Editorial");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Biblioteca.Modelos.Autor", b =>
                {
                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Biblioteca.Modelos.Editorial", b =>
                {
                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Biblioteca.Modelos.Genero", b =>
                {
                    b.Navigation("Libro");
                });
#pragma warning restore 612, 618
        }
    }
}
